In [1]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv('./Resources/Final_Data.csv')
df

,Zip_Code,Date,Year,Month,Sale_Price,Interest_Rate,Property_Tax,Rent_Price,Household_Income,Rent_Affordability,...,FTE_Employed,Unemployed,Expense_Index,Average_Commute,Crime_Index,Loan_Amount,Loan_Term,Loan_R,Loan_Payment,Home_Affordability
0,32003,2019-01-01,2019,1,244950.0,4.4640,3778,1113,94154.0,0.141853,...,10671,1069,104,35,28,195960.0,360.0,1.003720,988.713278,0.126012
1,32003,2019-02-01,2019,2,270000.0,4.3700,3778,1113,94154.0,0.141853,...,10671,1069,104,35,28,216000.0,360.0,1.003642,1077.819242,0.137369
2,32003,2019-03-01,2019,3,275000.0,4.2650,3778,1113,94154.0,0.141853,...,10671,1069,104,35,28,220000.0,360.0,1.003554,1084.200547,0.138182
3,32003,2019-04-01,2019,4,264500.0,4.1425,3778,1113,94154.0,0.141853,...,10671,1069,104,35,28,211600.0,360.0,1.003452,1027.671397,0.130978
4,32003,2019-05-01,2019,5,281000.0,4.0720,3778,1113,94154.0,0.141853,...,10671,1069,104,35,28,224800.0,360.0,1.003393,1082.581718,0.137976
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21759,34997,2020-10-01,2020,10,285000.0,2.8340,3067,1211,58789.0,0.247189,...,15421,1267,91,24,113,228000.0,360.0,1.002362,940.965557,0.192070
21760,34997,2020-11-01,2020,11,259750.0,2.7650,3067,1211,58789.0,0.247189,...,15421,1267,91,24,113,207800.0,360.0,1.002304,849.977103,0.173497
21761,34997,2020-11-01,2020,11,259750.0,2.7650,3067,1211,58789.0,0.247189,...,15421,1267,91,24,113,207800.0,360.0,1.002304,849.977103,0.173497
21762,34997,2020-12-01,2020,12,297000.0,2.6840,3067,1211,58789.0,0.247189,...,15421,1267,91,24,113,237600.0,360.0,1.002237,961.694879,0.196301
21763,34997,2020-12-01,2020,12,297000.0,2.6840,3067,1211,58789.0,0.247189,...,15421,1267,91,24,113,237600.0,360.0,1.002237,961.694879,0.196301

In [17]:
df = df.drop_duplicates()

In [18]:
df1 = df.assign(delta_A=df.Sale_Price.diff().fillna(0).astype(int))
df1

,Zip_Code,Date,Year,Month,Sale_Price,Interest_Rate,Property_Tax,Rent_Price,Household_Income,Rent_Affordability,...,Unemployed,Expense_Index,Average_Commute,Crime_Index,Loan_Amount,Loan_Term,Loan_R,Loan_Payment,Home_Affordability,delta_A
0,32003,2019-01-01,2019,1,244950.0,4.4640,3778,1113,94154.0,0.141853,...,1069,104,35,28,195960.0,360.0,1.003720,988.713278,0.126012,0
1,32003,2019-02-01,2019,2,270000.0,4.3700,3778,1113,94154.0,0.141853,...,1069,104,35,28,216000.0,360.0,1.003642,1077.819242,0.137369,25050
2,32003,2019-03-01,2019,3,275000.0,4.2650,3778,1113,94154.0,0.141853,...,1069,104,35,28,220000.0,360.0,1.003554,1084.200547,0.138182,5000
3,32003,2019-04-01,2019,4,264500.0,4.1425,3778,1113,94154.0,0.141853,...,1069,104,35,28,211600.0,360.0,1.003452,1027.671397,0.130978,-10500
4,32003,2019-05-01,2019,5,281000.0,4.0720,3778,1113,94154.0,0.141853,...,1069,104,35,28,224800.0,360.0,1.003393,1082.581718,0.137976,16500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21754,34997,2020-08-01,2020,8,251000.0,2.9350,3067,1211,58789.0,0.247189,...,1267,91,24,113,200800.0,360.0,1.002446,839.557908,0.171370,-4000
21756,34997,2020-09-01,2020,9,256000.0,2.8900,3067,1211,58789.0,0.247189,...,1267,91,24,113,204800.0,360.0,1.002408,851.342725,0.173776,5000
21758,34997,2020-10-01,2020,10,285000.0,2.8340,3067,1211,58789.0,0.247189,...,1267,91,24,113,228000.0,360.0,1.002362,940.965557,0.192070,29000
21760,34997,2020-11-01,2020,11,259750.0,2.7650,3067,1211,58789.0,0.247189,...,1267,91,24,113,207800.0,360.0,1.002304,849.977103,0.173497,-25250
21762,34997,2020-12-01,2020,12,297000.0,2.6840,3067,1211,58789.0,0.247189,...,1267,91,24,113,237600.0,360.0,1.002237,961.694879,0.196301,37250

In [5]:
delta = pd.Series(index=['delta'])
for index, row in data.iterrows():
#     print(index)
#     print(row['Zip_Code'])
    row2 = row + 1
    if (row["Zip_Code"] == [row+1]["Zip_Code"]):
        print(row['Zip_Code'])
#         delta[index] = data[index+1]["Sales_Price"]-data[index]["Sale_Price"]
# data["delta"] = delta

<ipython-input-5-32a0dacc187f>:1: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  delta = pd.Series(index=['delta'])

TypeError: can only concatenate str (not "int") to str